spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classroom
    username: root
    password:
    hikari:
      minimumIdle: 1
      maximumPoolSize: 8
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create


## If default port already in use
server:
  port: 8081
  ## Session timeout
  servlet:
    session:
      timeout: 300s
