spring:
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_62e9fedd716cac1
    username: b92419f7b42828
    password: f36769ba
    hikari:
      minimumIdle: 1
      maximumPoolSize: 8
  jpa:
    hibernate:
      ddl-auto: update

## If default port already in use
server:
  port: 8081
  ## Session timeout
  servlet:
    session:
      timeout: 300s
